### ISSUE TITLE
AST types design (Syntax module) is poor

### ISSUE THREAD

**Issue by leventov** [vincenthz/language-java#30]
I'm sure if anybody tried to use it, i. e. to construct AST programmatically, he can prove that it is hard, painful.

- It tends to unnecessarily divide unit abstractions between data types and constructors, e. g. `Stmt` and `BlockStmt`
- It tends to define intermediate wrapper data types, simplest example is `data Ident = Ident String`. I understand it is supposed for "type safety", but generally design of this module allows to construct illegal Java source very easily (it could do better on this, though, but anyway this is not a priority for this module, because we anyway are going to compile Java source and java compiler will tell us we generated something wrong), so this is a highly doubtful goal.

The result of the two above points, if I want to generate a trivial statement like `int a = 0;`, I should write
```
import Language.Java.Syntax as J

J.LocalVars [] (J.PrimType J.IntT)
    [J.VarDecl (J.VarId $ J.Ident "a") $ Just $ J.InitExp (J.Lit (J.Int 0))]
```

No comment.

- Cryptic constructor names, for example of `MethodCall` data type. It's `MethodCall`, `PrimaryMethodCall`, `SuperMethodCall`, `ClassMethodCall` and `TypeMethodCall` (I especially like the last two ones) should be `ImplicitlyTargetedMethodCall` (or `NotTargetedMethodCall`), `ExpressionTargetedMethodCall`, `UnqualifiedSuperMethodCall`, `QualifiedSuperMethodCall`, `TypeTargetedMethodCall`. You may say the names are too long, but it raises the question if we actually need all five different constructors? See the point 1.

- Absence of documentation. See
```
data ForInit = ForLocalVars [Modifier] Type [VarDecl]
             | ForInitExps [Exp]
```

I consider myself a Java programmer with syntax "on my fingers", but I don't understand the defference between these two constructors. There is no documentation. Previously, looking at pretty-printing definition helped me in such cases, but now I see
```
instance Pretty ForInit where
  prettyPrec p (ForLocalVars mods t vds) =
    hsep $ map (prettyPrec p) mods ++
            prettyPrec p t: punctuate comma (map (prettyPrec p) vds)
  prettyPrec p (ForInitExps es) =
    hsep $ punctuate comma (map (prettyPrec p) es)
```

So what? :)

(BTW. Why we have additional intermediate `BasicFor (Maybe ForInit) ...`, If I can construct just `ForInitExps []`?)

### Conclusion

I know you can say "write better". I don't have time for this, now. But I have time to complain, and maybe draw some attention. If anybody reach this, some links for guidance:

- Mature Java AST projects in Java, e. g. https://github.com/INRIA/spoon or https://github.com/square/javapoet, for hints how Java AST abstractions should actually be designed.

- How to design APIs: http://www.infoq.com/articles/API-Design-Joshua-Bloch (this is about Java, but applies to any language largely). Let me highlight the most meaningful points, in Haskell context:

  - APIs should be self-documenting
  - **It should be easy to do simple things**; possible to do complex things; and impossible, or at least difficult, to do wrong things.
  - When designing an API, first gather requirements. **You should clearly understand the use-cases of this API, and how the API helps to reach the goals of it's users.**
  - Names matter
  - Documentation matters
  - **Don't make the client do anything the library could do**
  - Use consistent parameter ordering across methods

**Comment by vincenthz** [comment]
if you don't like something, improve it/fork it. I don't think condescending "how-to-design-X" issue helps in any way (unless the project is actively asking for it).

**Comment by leventov** [comment]
@vincenthz Sorry for tone, it was inappropriate. The lack of documentation is an objective thing.

**Comment by vincenthz** [comment]
I really don't disagree with some of the many things you said (certainly documentation is not enough, and some design choices are questionable), but it's a community maintained library; it's only as good at the amount of work people put in it. (I can't put any active work in it, but still happy to review patches and make release)
