### ISSUE TITLE
parser does not support java annotations

### ISSUE THREAD

**Issue by marcelosousa** [vincenthz/language-java#43]
When trying to run the parser over the Java file:
https://github.com/datastax/java-driver/blob/3.0/driver-core/src/test/java/com/datastax/driver/core/utils/CassandraVersion.java

One gets the error:
unexpected KW_Interface

Do you expect to support annotations soon?

Thanks a lot for this great package!

**Comment by vincenthz** [comment]
There's no plan to add them that I know of, but if anyone is interested to add them and make a PR then it will certainly be reviewed and added

**Comment by dajmaki** [comment]
Here's a try: https://github.com/vincenthz/language-java/pull/45

**Comment by dvekeman** [comment]
+1 
I cherry-picked the commit and was ok for me.

**Comment by dvekeman** [comment]
This can be closed, it's merged now. Thanks!
