### ISSUE TITLE
Cannot parse method references on `this`

### ISSUE THREAD

**Issue by drever** [vincenthz/language-java#64]
The MethodRefs are defined to be identifiers. However, Java allows to use `this` as the class of the method reference. 

This works:

     parser Language.Java.Parser.exp "MyClass::myMethod"
     > Right (MethodRef (Ident "MyClass") (Ident "myMethod"))

This also:

     parser Language.Java.Parser.exp "otherInstance::myMethod"
     > Right (MethodRef (Ident "otherInstance") (Ident "myMethod"))

This does not:

    parser Language.Java.Parser.exp "this::myMethod"
    > Right This

Regards
Johannes

**Comment by ropwareJB** [comment]
Probably too late to address this particular ticket as it is four years old, however future readers should be directed to my fork which has this issue addressed:
https://github.com/Montycarlo/language-java
