### ISSUE TITLE
Incorrect parentheses in pretty printer

### ISSUE THREAD

**Issue by twanvl** [vincenthz/language-java#65]
The pretty printer doesn't take operator fixity into account. For example

    prettyPrint $ BinOp (Lit (Int 1)) Sub (BinOp (Lit (Int 2)) Sub (Lit (Int 3)))

outputs `"1 - 2 - 3"`, but it should be `"1 - (2 - 3)"`.

**Comment by drever** [comment]
Is this project still alive? This issue is the only activity in this year and the ticket #64 I opened a year ago has no answers.
